runtime: python39  # Menggunakan runtime standar untuk hosting HTML statis
service: fe-notessyifa  # Nama layanan App Engine, bisa diubah sesuai kebutuhan
instance_class: F1  # Kelas instance untuk App Engine (F1 adalah kelas standar yang ringan)

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  # Serve file js
  - url: /js/(.*)
    static_files: js/\1
    upload:
      js/(.*)

  - url: /(.*)
    static_files: \1
    upload: (.*)

default_expiration: "1h"  # Waktu cache default