runtime: python39
service: fe-notessyifa
instance_class: F1

handlers:
  - url: /register.html
    static_files: register.html
    upload: register.html

  - url: /login.html
    static_files: login.html
    upload: login.html

  - url: /index.html
    static_files: index.html
    upload: index.html

  - url: /js/(.*)
    static_files: js/\1
    upload: js/(.*)

  #  tampilkan register.html
  - url: /
    static_files: register.html
    upload: register.html

  # Backup: tangani file lain
  - url: /(.*)
    static_files: \1
    upload: (.*)

default_expiration: "1h"
